In [ ]:
import torch

In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
import random

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
random_seed=100
random.seed(random_seed)
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [ ]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
model=BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [ ]:
text1 = "Focus is the key to success"
text2 = "Mohun Bagan all the way"

In [ ]:
encoding=tokenizer.batch_encode_plus([text1, text2],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [ ]:
input_ids=encoding["input_ids"]

In [ ]:
input_ids

tensor([[  101,  3579,  2003,  1996,  3145,  2000,  3112,   102,     0],
        [  101,  9587, 17157,  4524,  2319,  2035,  1996,  2126,   102]])

In [ ]:
attention_mask=encoding["attention_mask"]

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
token_type_ids=encoding["token_type_ids"]

In [ ]:
token_type_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
with torch.no_grad():
  outputs = model(input_ids,attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [ ]:
word_embeddings.shape

torch.Size([2, 9, 768])

In [ ]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [ ]:
decode

'focus is the key to success'

In [ ]:
decode1=tokenizer.decode(input_ids[1],skip_special_tokens=True)

In [ ]:
decode1

'mohun bagan all the way'